# Screen #
NAME = "Tower Defense Game"
SCREEN_WIDTH = 590
SCREEN_HEIGHT = 695
MARGIN = 5
FRAMES_PER_SECOND = 30
WHITE = (255, 255, 255)
BG_COLOR = (221, 198, 89)#(200, 200, 200)
O_COLOR = (27, 143, 30)#(100, 100, 100)
FONT = "helvetica"
FONT_SIZE = 14
FONT_COLOR = (27, 143, 30)#(0, 200, 0)
SELECTED_O_COLOR = (225, 225, 55)
SELECTED_O_WIDTH = 2
WORLD_PATH = "../assets/worlds/"
SPLASH_PATH = "../assets/images/splash/"
BUTTON_PATH = "../assets/images/buttons/"
TOWER_PATH = "../assets/images/towers/"
BULLET_PATH = "../assets/images/bullets/"
CREEP_PATH = "../assets/images/creeps/"
TILE_PATH = "../assets/images/tiles/"

# Alert #
ALERT_O_COLOR = O_COLOR
ALERT_BG_COLOR = BG_COLOR
ALERT_MARGIN_X = 5
ALERT_MARGIN_Y = 5
ALERT_OUTLINE_WIDTH = 3
ALERT_FONT = FONT
ALERT_FONT_SIZE = FONT_SIZE
ALERT_FONT_COLOR = FONT_COLOR
### failure ###
ALERT_FAILURE_WIDTH = 400
ALERT_FAILURE_HEIGHT = 50
ALERT_FAILURE_POS = ((SCREEN_WIDTH - ALERT_FAILURE_WIDTH)/2.0, (SCREEN_HEIGHT - ALERT_FAILURE_HEIGHT)/3.0)
ALERT_FAILURE_MESSAGE = "Failure! You have failed to complete all of the waves on this level. Click anywhere to return to the main menu."
### success ###
ALERT_SUCCESS_WIDTH = 400
ALERT_SUCCESS_HEIGHT = 50
ALERT_SUCCESS_POS = ((SCREEN_WIDTH - ALERT_SUCCESS_WIDTH)/2.0, (SCREEN_HEIGHT - ALERT_SUCCESS_HEIGHT)/3.0)
ALERT_SUCCESS_MESSAGE = "Congratulations! You have completed this level! Click anywhere to return to main menu."

# Menu #
MENU_O_COLOR = O_COLOR
MENU_BG_COLOR = BG_COLOR
MENU_P_X = 7
MENU_P_Y = 538
MENU_P_WIDTH = 348
MENU_P_HEIGHT = 50
MENU_B_X = 7
MENU_B_Y = 593
MENU_B_WIDTH = 348
MENU_B_HEIGHT = 77
MENU_P_O_COLOR = O_COLOR
MENU_P_BG_COLOR = BG_COLOR
MENU_B_O_COLOR = O_COLOR
MENU_B_BG_COLOR = BG_COLOR
MENU_ITEM_MARGIN_X = 10
MENU_ITEM_MARGIN_Y = 10
MENU_OUTLINE_WIDTH = 3
### Main menu ###
MM_WIDTH = SCREEN_WIDTH - 2*MARGIN
MM_HEIGHT = 75
MM_POS = (MARGIN, SCREEN_HEIGHT-MM_HEIGHT)
MM_BG_COLOR = (221, 198, 89)
MM_O_COLOR = (27, 143, 30)
MM_IMG = SPLASH_PATH + "logo.png"
MM_IMG_POS = (0, 0)
### Level select ###
LS_IMG = SPLASH_PATH + "level_select.png"
LS_IMG_WIDTH = 580
LS_IMG_HEIGHT = 110
LS_WIDTH = SCREEN_WIDTH - 2*MARGIN
LS_HEIGHT = SCREEN_HEIGHT - MARGIN - MM_HEIGHT
LS_POS = (MARGIN, MARGIN)
LS_BG_COLOR = (221, 198, 89)
LS_O_COLOR = (27, 143, 30)

# Display #
DISPLAY_FONT = "helvetica"
DISPLAY_FONT_SIZE = 12
DISPLAY_FONT_COLOR = (27, 143, 30)
DISPLAY_X = 360
DISPLAY_Y = 538
DISPLAY_O_COLOR = O_COLOR
DISPLAY_BG_COLOR = BG_COLOR
DISPLAY_HEIGHT = 132
DISPLAY_WIDTH = 223
DISPLAY_MARGIN_LEFT = 5
DISPLAY_MARGIN_TOP = 5
DISPLAY_NO_IMG_HEIGHT = 32
DISPLAY_NO_IMG_WIDTH = 32

# Button menu #
MENU_BUTTON_HEIGHT = 77

# Menu Buttons #
BUTTON_NEW_WAVE_IMG = BUTTON_PATH + "nextWave.png"
BUTTON_NEW_WAVE_HOVER_IMG = BUTTON_PATH + "nextWave_hover.png"
BUTTON_NEW_WAVE_WIDTH = 75
BUTTON_NEW_WAVE_HEIGHT = 45
BUTTON_UPGRADE_IMG = BUTTON_PATH + "upgrade.png"
BUTTON_UPGRADE_HOVER_IMG = BUTTON_PATH + "upgrade_hover.png"
BUTTON_UPGRADE_WIDTH = 75
BUTTON_UPGRADE_HEIGHT = 45
BUTTON_SELL_IMG = BUTTON_PATH + "sell.png"
BUTTON_SELL_HOVER_IMG = BUTTON_PATH + "sell_hover.png"
BUTTON_SELL_WIDTH = 75
BUTTON_SELL_HEIGHT = 45
BUTTON_PLAY_IMG = BUTTON_PATH + "play.png"
BUTTON_PLAY_HOVER_IMG = BUTTON_PATH + "play_hover.png"
BUTTON_PLAY_WIDTH = 75
BUTTON_PLAY_HEIGHT = 45
BUTTON_QUIT_IMG = BUTTON_PATH + "quit.png"
BUTTON_QUIT_HOVER_IMG = BUTTON_PATH + "quit_hover.png"
BUTTON_QUIT_WIDTH = 75
BUTTON_QUIT_HEIGHT = 45
BUTTON_LEVEL_IMG = BUTTON_PATH + "level.png"
BUTTON_LEVEL_HOVER_IMG = BUTTON_PATH + "level_hover.png"
BUTTON_LEVEL_WIDTH = 75
BUTTON_LEVEL_HEIGHT = 45

# Hardware Buttons #
DUPLICATE_BUTTONS = [303, 304] # left and right shift buttons
MOUSE_LEFT = 1
MOUSE_MIDDLE = 2
MOUSE_RIGHT = 3

# enums #

## game_logic actions ##
P_IDLE = 4
P_FOLLOW = 5
P_PLACE = 6
T_SELECTED = 7
T_FIRE = 8
B_DONE = 9
B_KILL = 10
C_DEAD = 11
C_SELECTED = 12

## Sub states ##
TD_IDLE = 13
TD_FOLLOW = 14
TD_SHOW = 15

## States ##
TD_MENU = 16
TD_LEVEL_SELECT = 17
TD_PAUSE = 18
TD_PLAYING = 19 # wave in progress
TD_CLEAR = 20 # in between waves
TD_FAILURE = 21
TD_SUCCESS = 22

## Menu Buttons ##
BUTTON_NEW_WAVE_MSG = 23
BUTTON_UPGRADE_MSG = 24
BUTTON_SELL_MSG = 25
BUTTON_PLAY_MSG = 26
BUTTON_QUIT_MSG = 27
BUTTON_LEVEL_MSG = 28

# instructions #
P_SNAP_LOC = 29

# kinds #
KIND_TOWER = 30
KIND_CREEP = 31
KIND_TILE = 32
KIND_BUTTON = 33
KIND_BULLET = 34

# alert #
ALERT_EXP_MESSAGE = 35

# Healthbar #
HEALTH_BAR_WIDTH = 20
HEALTH_BAR_HEIGHT = 5
HEALTH_BAR_BG_COLOR = (225, 0, 0)
HEALTH_BAR_COLOR = (0, 225, 0)
HEALTH_BAR_MARGIN = 3

# Tower #
RANGE_COLOR = (50, 255, 50, 125)
RANGE_BAD_COLOR = (255, 50, 50, 125)

TOWER_BASIC_IMAGE = TOWER_PATH + "basic.png"
TOWER_BASIC_WIDTH = 32
TOWER_BASIC_HEIGHT = 32
TOWER_BASIC_COST = [25, 50, 75, 100]
TOWER_BASIC_RANGE = [70, 80, 90, 100]
TOWER_BASIC_ATK_SPEED = [2, 2.5, 2.75, 3]
TOWER_BASIC_DAMAGE = [25, 50, 100, 175]
TOWER_GREEN_IMAGE = TOWER_PATH + "green.png"
TOWER_GREEN_WIDTH = 16
TOWER_GREEN_HEIGHT = 16
TOWER_GREEN_COST = [15, 25, 35, 50]
TOWER_GREEN_RANGE = [50, 60, 70, 80]
TOWER_GREEN_ATK_SPEED = [7, 7.5, 8, 8.5]
TOWER_GREEN_DAMAGE = [8, 16, 32, 64]

# Bullet #
BULLET_BASIC_IMAGE = BULLET_PATH + "basic.png"
BULLET_BASIC_WIDTH = 8
BULLET_BASIC_HEIGHT = 8
BULLET_BASIC_SPEED = 300
BULLET_GREEN_IMAGE = BULLET_PATH + "green.png"
BULLET_GREEN_WIDTH = 4
BULLET_GREEN_HEIGHT = 4
BULLET_GREEN_SPEED = 300

# Money #
STARTING_MONEY = 100000000
MONEY_X = MARGIN
MONEY_Y = 675

# Lives #
STARTING_LIVES = 10
LIVES_X = MARGIN + 217
LIVES_Y = 675

# Wave #
WAVE_X = MARGIN*2 + 434
WAVE_Y = 675
WAVES = [[0], [10, 1], [15, 3], [0, 15]]

# Creep #
CREEP_GAP = 15
CREEP_COUNT = 2
CREEP_DEFAULT_HEALTH = 100
CREEP_DEFAULT_NAME = "Red Creep"
CREEP_DEFAULT_SPEED = 75
CREEP_DEFAULT_IMAGE = CREEP_PATH + "creep.png"
CREEP_DEFAULT_WIDTH = 16
CREEP_DEFAULT_HEIGHT = 16
CREEP_DEFAULT_VALUE = 10

CREEP_YELLOW_HEALTH = 500
CREEP_YELLOW_NAME = "Yellow Creep"
CREEP_YELLOW_SPEED = 50
CREEP_YELLOW_IMAGE = CREEP_PATH + "yellow.png"
CREEP_YELLOW_WIDTH = 16
CREEP_YELLOW_HEIGHT = 16
CREEP_YELLOW_VALUE = 50

# World #
WORLD_X = 7
WORLD_Y = 5
WORLD_WIDTH = 576
WORLD_HEIGHT = 528
WORLD1_PATH = WORLD_PATH + "world1.txt"
WORLD1_NAME = "Level 1"
WORLD2_PATH = WORLD_PATH + "world2.txt"
WORLD2_NAME = "Level 2"
PATH_IMG = TILE_PATH + "path.png"
GRASS_IMG = TILE_PATH + "grass_outlined.png"
TILE_WIDTH = 16
TILE_HEIGHT = 16
WORLD_DEFAULT_WIDTH = 576
WORLD_DEFAULT_HEIGHT = 528

LEVELS = [(WORLD1_PATH, WORLD1_NAME), (WORLD2_PATH, WORLD2_NAME)]
